# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='User',
        ),
    ]
